### ISSUE TITLE
TS error after updating from 2.0.2 to 2.0.3

### ISSUE THREAD

**Issue by volkerrichert** [compwright/axios-oauth-client#29]
After updateing to 2.0.3 i got the following error:

```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("axios-oauth-client")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '.../package.json'.

3 import oauthClient from 'axios-oauth-client';

```

Any Idea how to fix this? 2.0.2 works fine.

THX,

Volker

**Comment by compwright** [comment]
We already compile this to an ES module. You could try:

```javascript
import oauthClient from 'axios-oauth-client/dist/index.mjs';
```

If that doesn't work then it is an issue with your project config, not this package or version.

**Comment by volkerrichert** [comment]
maybe there is a problem with my config, but can you help me?

if i change your exports in the package.json to

```
"exports": {
    ".": {
      "types": {
        **".": "./dist/index.d.ts"**
      },
      "import": "./dist/index.mjs",
      "require": "./dist/index.cjs"
    }
  },
``` 
it compiles fine. Can you give me a hint?

**Comment by compwright** [comment]
@volkerrichert please try v2.0.4, and see if that fixes your issue.

**Comment by volkerrichert** [comment]
Yes, that compiles. Can you explain the difference?
